dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk10
  - openjdk10
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: latest

env:
- TOMCAT_VERSION=9.0.10
- TOMCAT_VERSION=8.5.32
- TOMCAT_VERSION=8.0.53

before_script:
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-*.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Downloading chrome..."
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

install:
- ./mvnw -B clean validate
- wget http://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_VERSION:0:1}/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.zip
- unzip apache-tomcat-$TOMCAT_VERSION.zip
- chmod a+x apache-tomcat-$TOMCAT_VERSION/bin/*.sh
- apache-tomcat-$TOMCAT_VERSION/bin/catalina.sh start

script:
  - ./mvnw -B -Pcheck-duplicate,check-checkstyle,check-cycles,check-cpd,check-pmd,check-findbugs -DskipTests=true install
#  - /usr/bin/xvfb-run ./mvnw -DwebDriverType=firefox verify
  - /usr/bin/xvfb-run ./mvnw -DwebDriverType=chrome verify
  - cp -v target/joinfaces-example-*.war  apache-tomcat-$TOMCAT_VERSION/webapps/joinfaces-maven-war-example.war
  - timeout --preserve-status 60s tail -f apache-tomcat-$TOMCAT_VERSION/logs/catalina.out || true
  - wget localhost:8080/joinfaces-maven-war-example/index.xhtml

after_success:
  - bash <(curl -s https://codecov.io/bash)

