language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
addons:
  firefox: "55.0"
  apt:
    packages:
      - oracle-java8-installer
before_script:
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-55.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Downloading chrome..."
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - echo "Downloading maven and setting PATH variable..."
  - wget http://apache.claz.org/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
  - tar zxvf apache-maven-3.5.0-bin.tar.gz
  - chmod +x apache-maven-3.5.0/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$PWD/apache-maven-3.5.0/bin:${PATH}  
